#!/bin/sh
#
#	icecast 

case "$1" in
	start)
		echo "Iniciado el Icecast"
		mkdir /var/log/icecast/ 2> /dev/null
		touch /var/log/icecast/error.log 2> /dev/null
		touch /var/log/icecast/access.log 2> /dev/null
		chown nobody /var/log/icecast/*

		/usr/bin/icecast -c /etc/icecast.xml -b &
		echo "."
		;;
	stop)
		killall icecast
		echo "."
		;;
	restart)
		echo "Reiniciando el Icecast"
		$0 stop
		$0 start
		echo "."
		;;
	*)
		echo "Uso: $0 {start|stop|restart}"
		exit
		;;
esac
exit 0
