#!/bin/sh
#
#	intenta conectar a una red abiertas o de las cuales se conosca las claves
#	Ernesto Bazzano (c) Liberado bajo AGPL
#

#--------------------- variables ---------------------------

BIN="/root/mallacritica/"
PATH="$PATH:$BIN"

SHARE="/usr/share/mallacritica"
CLAVES="$SHARE/wireless-claves"

PING="208.80.152.201"	#wikipedia


#--------------------- funciones --------------------------

conectado () {
	# verifica si esta conectado
	if [ ! "$(ping -W 2 -c 1 $PING 2>&1| grep unreachable)" ]; then
		echo "¡se conecto!"
		led 2000 1000
		exit
	else
		echo "no pude conectar"
		led 100 100
	fi
}

reinciar () {
	# reinicia el wifi
	wifi down
	wifi up
	sleep 5
}

wifi_dispositivo () {
		# carga la configuracion de la placa de wifi del equipo
		rm -f /etc/config/wireless
		wifi detect | grep -B 1000 "REMOVE"  > /etc/config/wireless
}


#--------------------- verifica si esta conectado ---------------------------

conectado

#--------------------- archivos por defecto ---------------------------

# lo crea si no existe
mkdir -p "$SHARE" 2> /dev/null
touch "$SHARE/wireless-claves" 2> /dev/null

if [ ! -f "$SHARE/wireless-defecto" ]; then
	echo "Creando la configuracion por defecto"
	cp /etc/config/wireless "$SHARE/wireless-defecto"
fi

# --------- buscador de redes ----------

# Lista de redes visibles
wireless_lista | while read AP; do

	# SSID, hay que mejorarlo un poco
	SSID=$(echo $AP | cut -d " " -f 2-4 | sed 's/\ Authentication.*$//g')
	WAP=$(echo $AP | grep PSK)

	# busca una clave de la lista

	grep -i "^${$SSID:0:4}" $CLAVES | cut -d"\t" -f2 | while read KEY; do

		echo "Conectando a '$SSID' clave '$KEY'"

		# Si tiene la clave guardada
		if [ "$KEY" ]; then
			if [ "$WAP" ]; then
				echo "codificación WAP"
				ENCRYPTION='psk'
			else
				echo "codificación WEP"
				ENCRYPTION='wep'
			fi
			wifi_dispositivo
			cat "$SHARE/wireless-config" | sed "s/\$SSID/$SSID/g; s/\$ENCRYPTION/$ENCRYPTION/g; s/\$KEY/$KEY/g" >> /etc/config/wireless
			reinciar
			conectado
		else
			if [ "$WAP" ]; then
				# si es WAP no se gasta ni en probar, si no tiene la clave
				break
			fi
			# Intenta conectar sin clave por las dudas
			ENCRYPTION='none'
			#KEY=''
			wifi_dispositivo
			cat "$SHARE/wireless-config" | sed "s/\$SSID/$SSID/g; s/\$ENCRYPTION/$ENCRYPTION/g;" >> /etc/config/wireless
			reinciar
			conectado
		fi
	done
done

#------------------------si no logra conectarse a anda------------------------

conectado
wifi_dispositivo
# vuelve a la configuracion por defecto
cp "$SHARE/wireless-defecto" >> /etc/config/wireless
reinciar

exit

Por hacer:

	- hacer mas simple el programa
	- verificar la calidad de servicio.
	- verficiar si realmente es internet.
	- programa en background para romper redes
	- desconectar a lo clientes para tener mas ancho de banda (?)
	- hacer que tenga indicadores por luz